# name: fanexp
# description: "A new Flutter project."
# publish_to: 'none'

# version: 1.0.0+1

# environment:
#   sdk: ^3.9.2

# dependencies:
#   flutter:
#     sdk: flutter
#   flutter_localizations:
#     sdk: flutter

#   # UI & utilitaires
#   cupertino_icons: ^1.0.8
#   intl_phone_number_input: ^0.7.5
#   fluttertoast: ^9.0.0
#   shared_preferences: ^2.5.3
#   persistent_bottom_nav_bar: ^6.2.1
#   form_field_validator: ^1.1.0
#   steps_indicator: ^1.3.0
#   flutter_typeahead: ^5.2.0
#   assets_audio_player: ^3.1.1
#   lottie: ^3.3.2
#   provider: ^6.1.5
#   flutter_local_notifications: ^19.5.0
#   # video_player: ^2.9.2
#   flutter_tts: ^3.8.3
#   flutter_map: ^6.1.0
#   latlong2: ^0.9.0
#   http: ^1.2.2

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^5.0.0
#   flutter_launcher_icons: ^0.14.4

# # Configuration de l’icône de lancement
# flutter_icons:
#   android: true
#   ios: true
#   image_path: assets/img/launchericon.jpeg
#   adaptive_icon_background: "#FFFFFF"
#   adaptive_icon_foreground: assets/img/launchericon.jpeg
#   remove_alpha_ios: true

# flutter:
#   uses-material-design: true
#   flutter_icons:
#     android: true
#     ios: true
#     image_path: "assets/img/launchericon.jpeg"
#     remove_alpha_ios: true
#     adaptive_icon_background: "#F9B233" # ton or Gaïndé
#     adaptive_icon_foreground:  "assets/img/launchericon.jpeg"


#   assets:
#     - assets/img/
#     - assets/animations/
#     - assets/audios/


name: fanexp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & utilitaires
  cupertino_icons: ^1.0.8
  intl_phone_number_input: ^0.7.5
  fluttertoast: ^9.0.0
  shared_preferences: ^2.5.3
  persistent_bottom_nav_bar: ^6.2.1
  form_field_validator: ^1.1.0
  steps_indicator: ^1.3.0
  flutter_typeahead: ^5.2.0
  assets_audio_player: ^3.1.1
  lottie: ^3.3.2
  provider: ^6.1.5
  flutter_local_notifications: ^19.5.0
  # video_player: ^2.9.2
  
  flutter_tts: ^3.8.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

# ---- Icône de l'appli (UN SEUL bloc, au niveau racine) ----
flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/launchericon.jpeg"
  remove_alpha_ios: true
  adaptive_icon_background: "#F9B233"   # Or Gaïndé
  adaptive_icon_foreground: "assets/img/launchericon.jpeg"

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/animations/
    - assets/audios/
